이미지, 동영상 출처 : https://pixabay.com/ko/, https://www.pexels.com/ko-kr/

### 1. 이미지 읽기 옵션
   - cv2.IMREAD_COLOR : 컬러 이미지, 투명 영역은 무시(디폴트)
   - cv2.IMREAD_GRAYSCALE : 흑백 이미지
   - cv2.IMREAD_UNCHANGED : 투명 영역까지 포함

In [2]:
import cv2
import numpy as np
img_color = cv2.imread('cat.jpg', cv2.IMREAD_COLOR)
img_gray = cv2.imread('cat.jpg', cv2.IMREAD_GRAYSCALE)
img_unchanged = cv2.imread('cat.jpg', cv2.IMREAD_UNCHANGED)

cv2.imshow('img_color', img_color)
cv2.imshow('img_gray', img_gray)
cv2.imshow('img_unchanged', img_unchanged)
# 아무키를 눌러도 다운되지만 A를 누르면 출력문을 출력해준다.
if cv2.waitKey(0) == ord('A'):
    print('사용자에 의해 종료됨.')
cv2.destroyAllWindows()

사용자에 의해 종료됨.


In [3]:
img = cv2.imread('cat.jpg')
img.shape

(427, 640, 3)

### 2. 동영상 보여주기
- 동영상 파일 보여주기

In [3]:
import cv2 
cap = cv2.VideoCapture('cat.mp4')

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        print('더 이상 가져올 이미지가 없습니다.')
        break
    cv2.imshow('video', frame)
    if cv2.waitKey(30) == ord('q'):
        print('사용자에 의해 종료됨.')
        break

cap.release()
cv2.destroyAllWindows()

더 이상 가져올 이미지가 없습니다.


In [1]:
import cv2 
cap = cv2.VideoCapture(0)

while cap.isOpened():
    exit()
    ret, frame = cap.read()
    if not ret:
        break
    cv2.imshow('video', frame)
    if cv2.waitKey(30) == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

OpenCV: not authorized to capture video (status 0), requesting...
OpenCV: camera failed to properly initialize!
[ WARN:0@0.139] global cap_ffmpeg_impl.hpp:1217 open VIDEOIO/FFMPEG: Failed list devices for backend avfoundation


### 3. 도형 그리기
- 빈 스케치북 만들기

In [70]:
import cv2
import numpy as np
# 세로가 480 * 가로가 640, 3채널 [RGB]에 해당하는 빈 스케치북 만들기
# 검은색 창 만들기
img = np.zeros((480,640,3), dtype=np.uint8)
print(img)
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [71]:
import cv2
import numpy as np
# 흰색 창 만들기
img = np.zeros((480,640,3), dtype=np.uint8)
# 모든 요소를 255(흰색)로 채운 480x640 이미지 생성
# img = np.full((480, 640, 3), 255, dtype=np.uint8)
img[:] = 255  # 모든 픽셀을 255로 변경
print(img)
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [16]:
import cv2
import numpy as np
# 빨간 창 만들기
img = np.zeros((480,640,3), dtype=np.uint8)
img[:] = [0,0,255]  # bgr 순서 주의!!!!!!!!!!!!!!!!!!!
print(img)
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 ...

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]]


In [14]:
import cv2
import numpy as np
# 검은창에 흰색박스 만들기
img = np.zeros((480,640,3), dtype=np.uint8)
img[200:300, 300:400] = (255,255,255)
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 4. 직선 그리기
 - cv2.LINE_4 : 상하좌우 4가지 방향으로만 연결된 선
 - cv2.LINE_8 : 대각선을 포함한 8가지 방향으로 연결된 선(디폴트)
 - cv2.LINE_AA : 부드러운 선(anti-aliasing)

- cv2.line(그릴위치, 시작점, 끝점, 색깔, 두께, 선 종류)

In [19]:
import cv2
import numpy as np

img = np.zeros((480,640,3), dtype=np.uint8)
color = (0,255,255)
thic = 3

cv2.line(img, (50, 100), (400, 50), color, thic, cv2.LINE_4)
cv2.line(img, (50, 200), (400, 150), color, thic, cv2.LINE_8)
cv2.line(img, (50, 300), (400, 250), color, thic, cv2.LINE_AA)

cv2.imshow('line', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
import cv2
import numpy as np
# 검은창에 빨간 X 
img = np.zeros((480,640,3), dtype=np.uint8)
color = (0,0,255)
thic = 3

cv2.line(img, (0, 0), (640, 480), color, thic, cv2.LINE_AA)
# cv2.line(img, (50, 200), (400, 150), color, thic, cv2.LINE_8)
cv2.line(img, (0, 480), (640, 0), color, thic, cv2.LINE_AA)

cv2.imshow('line', img)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1) # macOS 전용 버그 픽스용 한 번 더 호출

-1

### 5. 원 그리기
  - cv2.circle(그릴위치, 원의 중심점, 반지름, 색깔, 두께, 선종류)

In [3]:
import cv2
import numpy as np
# 검은창에 빨간 X 
img = np.zeros((480,640,3), dtype=np.uint8)
color = (255,255,0)
thic = 10
radius = 50

cv2.circle(img, (300, 200), radius, color, thic, cv2.LINE_AA)
cv2.circle(img, (340, 200), radius, color, cv2.FILLED, cv2.LINE_AA)

cv2.imshow('circle', img)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1) # macOS 전용 버그 픽스용 한 번 더 호출

-1

### 6. 사각형 그리기
  - cv2.rectangle(그릴위치, 왼쪽위 좌표, 오른쪽 아래 좌표, 색깔, 두께)

In [6]:
import cv2
import numpy as np
# 검은창에 사각형 그리기
img = np.zeros((480,640,3), dtype=np.uint8)
color = (0,200,0)
thic = 3
radius = 50
cv2.line(img, (100, 400), (400, 100), (200,0,100), thic, cv2.LINE_AA)
# cv2.line(img, (100, 100), (400, 400), (200,0,100), thic, cv2.LINE_AA)
cv2.rectangle(img, (100, 100), (400, 400), color, thic)
cv2.rectangle(img, (250, 250), (350, 350), color, cv2.FILLED)
cv2.circle(img, (300, 200), radius, color, cv2.FILLED, cv2.LINE_AA)
cv2.line(img, (100, 100), (400, 400), (200,0,50), 10, cv2.LINE_AA)
cv2.putText(img, 'GoodBye World', (80, 70), cv2.FONT_HERSHEY_SIMPLEX, 2, (0, 255, 0), 3, cv2.LINE_AA)

cv2.imshow('circle', img)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1) # macOS 전용 버그 픽스용 한 번 더 호출

-1

### 7. 다각형 그리기
  - cv2.polylines(그릴위치, 그릴좌표들, 닫힘여부(T/F), 색깔, 두께, 선종류) : 비어있는 다각형
  - cv2.fillpoly(그릴위치, 그릴좌표들, 색깔, 선종류)

In [132]:
import cv2
import numpy as np

# 1. 초기 값 설정 (변수 정의 순서 주의!)
img_base = np.zeros((600, 600, 3), dtype=np.uint8) # 배경용
color = (0,200,0)
thic = 3
radius = 30
direction = 1

while True:
    
    cv2.putText(img, 'GoodBye World', (70, 70), cv2.FONT_HERSHEY_SIMPLEX, 2, (0, 255, 0), 3, cv2.LINE_AA)
    pt1 = np.array([[[100,100],[200,100],[100,200]], [[200,100],[300,100],[300,200]]])
    cv2.fillPoly(img, pt1, color, cv2.LINE_AA)
    pt2 = np.array([[[100,200],[100,300],[200,300]], [[200,300],[300,300],[300,200]]])
    cv2.polylines(img, pt2, True, color, 1, cv2.LINE_AA)
    
    pt3 = np.array([[[300,100],[400,100],[300,200]], [[300,200],[300,300],[400,300]]])
    cv2.polylines(img, pt3, True, color, 1, cv2.LINE_AA)
    pt4 = np.array([[[400,100],[500,100],[500,200]], [[500,200],[500,300],[400,300]]])
    cv2.fillPoly(img, pt4, color, cv2.LINE_AA)
    
    pt5 = np.array([[[300,300],[300,400],[400,300]], [[400,300],[500,300],[500,400]]])
    cv2.polylines(img, pt5, True, color, 1, cv2.LINE_AA)
    pt6 = np.array([[[300,400],[300,500],[400,500]], [[400,500],[500,500],[500,400]]])
    cv2.fillPoly(img, pt6, color, cv2.LINE_AA)
    
    pt7 = np.array([[[100,300],[200,300],[100,400]], [[100,400],[100,500],[200,500]]])
    cv2.fillPoly(img, pt7, color, cv2.LINE_AA)
    pt8 = np.array([[[200,300],[300,300],[300,400]], [[300,400],[300,500],[200,500]]])
    cv2.polylines(img, pt8, True, color, 1, cv2.LINE_AA)
    
    cv2.circle(img, (200, 200), radius, (200,200,0), cv2.FILLED, cv2.LINE_AA)
    cv2.circle(img, (400, 200), radius, (200,100,100), cv2.FILLED, cv2.LINE_AA)
    cv2.circle(img, (200, 400), radius, (100,200,100), cv2.FILLED, cv2.LINE_AA)
    cv2.circle(img, (400, 400), radius, (0,200,200), cv2.FILLED, cv2.LINE_AA)

    # 3. 중요!! 화면 보여주기를 루프 안으로 이동
    cv2.imshow('Animation', img)

    # 4. 로직 업데이트
    radius += direction
    if radius >= 50 or radius <= 30:
        direction *= -1

    # 5. 'q' 키를 누르면 종료 (30ms 대기 - 이 숫자가 작을수록 빨라짐)
    if cv2.waitKey(30) & 0xFF == ord('q'):
        break

# cv2.waitKey(0)
cv2.destroyAllWindows()

In [125]:
import cv2
import numpy as np

# 기본 설정
width, height = 600, 600
color = (0, 200, 0)
radius = 30
direction = 1  # 1이면 증가, -1이면 감소

while True:
    # 1. 매 프레임마다 배경을 다시 검은색으로 지우기 (안 지우면 잔상이 남음)
    img = np.zeros((height, width, 3), dtype=np.uint8)

    # 2. 현재 radius 값으로 원 그리기
    cv2.circle(img, (300, 300), radius, color, 3, cv2.LINE_AA)

    # 3. 화면 표시
    cv2.imshow('Animation', img)

    # 4. 반지름 값 업데이트
    radius += direction
    
    # 30~50 사이를 유지하도록 방향 전환
    if radius >= 50 or radius <= 30:
        direction *= -1

    # 5. 'q' 키를 누르면 종료 (30ms 대기 - 이 숫자가 작을수록 빨라짐)
    if cv2.waitKey(30) & 0xFF == ord('q'):
        break

cv2.destroyAllWindows()

In [131]:
import cv2
import numpy as np

# 1. 기본 설정
width, height = 600, 600
color = (0, 200, 0)
radius = 30
direction = 1

# 2. 좌표 데이터 미리 정의 (리스트 안에 담기)
# 채울 도형들 (Fill)
fill_list = [
    np.array([[[100,100],[200,100],[100,200]], [[200,100],[300,100],[300,200]]]), # pt1
    np.array([[[400,100],[500,100],[500,200]], [[500,200],[500,300],[400,300]]]), # pt4
    np.array([[[300,400],[300,500],[400,500]], [[400,500],[500,500],[500,400]]]), # pt6
    np.array([[[100,300],[200,300],[100,400]], [[100,400],[100,500],[200,500]]])  # pt7
]

# 테두리만 그릴 도형들 (Polyline)
line_list = [
    np.array([[[100,200],[100,300],[200,300]], [[200,300],[300,300],[300,200]]]), # pt2
    np.array([[[300,100],[400,100],[300,200]], [[300,200],[300,300],[400,300]]]), # pt3
    np.array([[[300,300],[300,400],[400,300]], [[400,300],[500,300],[500,400]]]), # pt5
    np.array([[[200,300],[300,300],[300,400]], [[300,400],[300,500],[200,500]]])  # pt8
]

while True:
    # 매 프레임 검은 도화지 준비
    img = np.zeros((height, width, 3), dtype=np.uint8)

    # 텍스트 출력
    cv2.putText(img, 'GoodBye World', (70, 70), cv2.FONT_HERSHEY_SIMPLEX, 2, (0, 255, 0), 3, cv2.LINE_AA)

    # 3. 반복문으로 한 번에 그리기 (코드가 엄청 짧아졌죠?)
    for poly in fill_list:
        cv2.fillPoly(img, poly, color, cv2.LINE_AA)

    for poly in line_list:
        cv2.polylines(img, poly, True, color, 1, cv2.LINE_AA)

    # 4. 애니메이션 원 그리기
    circle_centers = [(200, 200), (400, 200), (200, 400), (400, 400)]
    circle_colors = [(200, 200, 0), (200, 100, 100), (100, 200, 100), (0, 200, 200)]
    
    for i in range(4):
        cv2.circle(img, circle_centers[i], radius, circle_colors[i], cv2.FILLED, cv2.LINE_AA)

    # 화면 표시
    cv2.imshow('Pythonic OpenCV', img)

    # 로직 업데이트 (30~50 유지)
    radius += direction
    if radius >= 50 or radius <= 30:
        direction *= -1

    # 'q' 누르면 종료
    if cv2.waitKey(30) & 0xFF == ord('q'):
        break

cv2.destroyAllWindows()

In [2]:
import cv2
import numpy as np

# 1. 초기 설정
width, height = 800, 600 # x가 움직일 공간을 위해 가로를 조금 넓혔어요
color = (0, 200, 0)
radius = 30
rad_direction = 1

# x좌표 이동 관련 변수
offset_x = 0
x_direction = 1 # 1이면 오른쪽, -1이면 왼쪽

# 2. 원본 좌표 데이터 (0 위치 기준)
fill_list_raw = [
    np.array([[[100,100],[200,100],[100,200]], [[200,100],[300,100],[300,200]]]),
    np.array([[[400,100],[500,100],[500,200]], [[500,200],[500,300],[400,300]]]),
    np.array([[[300,400],[300,500],[400,500]], [[400,500],[500,500],[500,400]]]),
    np.array([[[100,300],[200,300],[100,400]], [[100,400],[100,500],[200,500]]])
]

line_list_raw = [
    np.array([[[100,200],[100,300],[200,300]], [[200,300],[300,300],[300,200]]]),
    np.array([[[300,100],[400,100],[300,200]], [[300,200],[300,300],[400,300]]]),
    np.array([[[300,300],[300,400],[400,300]], [[400,300],[500,300],[500,400]]]),
    np.array([[[200,300],[300,300],[300,400]], [[300,400],[300,500],[200,500]]])
]

circle_centers_raw = [(200, 200), (400, 200), (200, 400), (400, 400)]
circle_colors = [(200, 200, 0), (200, 100, 100), (100, 200, 100), (0, 200, 200)]

while True:
    img = np.zeros((height, width, 3), dtype=np.uint8)

    # 3. 모든 도형에 offset_x 적용 (Numpy 브로드캐스팅 활용)
    # 각 폴리곤 좌표에 [offset_x, 0]을 더해서 x축으로만 이동시킴
    for poly in fill_list_raw:
        moved_poly = poly + [offset_x, 0]
        cv2.fillPoly(img, moved_poly, color, cv2.LINE_AA)

    for poly in line_list_raw:
        moved_poly = poly + [offset_x, 0]
        cv2.polylines(img, moved_poly, True, color, 1, cv2.LINE_AA)

    # 4. 원 좌표 업데이트 및 그리기
    for i in range(4):
        cx, cy = circle_centers_raw[i]
        cv2.circle(img, (cx + offset_x, cy), radius, circle_colors[i], cv2.FILLED, cv2.LINE_AA)

    # 5. 상태 업데이트
    # 반지름 애니메이션
    radius += rad_direction
    if radius >= 50 or radius <= 30: rad_direction *= -1

    # X축 이동 애니메이션 (0 ~ 50)
    offset_x += x_direction
    if offset_x >= 200 or offset_x <= 0:
        x_direction *= -1

    cv2.imshow('Moving Shapes', img)
    if cv2.waitKey(10) & 0xFF == ord('q'):
        break

cv2.destroyAllWindows()
cv2.waitKey(1) # macOS 전용 버그 픽스용 한 번 더 호출

-1

In [ ]:
import cv2
import numpy as np

# 1. 초기 설정 (이전과 동일)
width, height = 800, 600 
color = (0, 200, 0)
radius = 30
rad_direction = 1

# x좌표 이동 관련 변수 (0 ~ 100으로 범위를 좀 넓혔어요)
offset_x = 0
x_direction = 1 # 1이면 오른쪽, -1이면 왼쪽

# 2. 원본 좌표 데이터 (이전 코드의 데이터를 그대로 사용하세요)
# (pt1 ~ pt8 좌표 데이터는 생략할게요. 위 코드의 raw 데이터를 그대로 넣어주세요.)
fill_list_raw = [
    np.array([[[100,100],[200,100],[100,200]], [[200,100],[300,100],[300,200]]]), # pt1
    np.array([[[400,100],[500,100],[500,200]], [[500,200],[500,300],[400,300]]]), # pt4
    np.array([[[300,400],[300,500],[400,500]], [[400,500],[500,500],[500,400]]]), # pt6
    np.array([[[100,300],[200,300],[100,400]], [[100,400],[100,500],[200,500]]])  # pt7
]

line_list_raw = [
    np.array([[[100,200],[100,300],[200,300]], [[200,300],[300,300],[300,200]]]), # pt2
    np.array([[[300,100],[400,100],[300,200]], [[300,200],[300,300],[400,300]]]), # pt3
    np.array([[[300,300],[300,400],[400,300]], [[400,300],[500,300],[500,400]]]), # pt5
    np.array([[[200,300],[300,300],[300,400]], [[300,400],[300,500],[200,500]]])  # pt8
]

circle_centers_raw = [(200, 200), (400, 200), (200, 400), (400, 400)]
circle_colors = [(200, 200, 0), (200, 100, 100), (100, 200, 100), (0, 200, 200)]

while True:
    img = np.zeros((height, width, 3), dtype=np.uint8)

    # 3. 중요!! 슬라이싱을 활용한 지그재그 그리기
    
    # --- 채울 도형들 (Fill) ---
    # 홀수 번째 (index 0, 2): 오른쪽으로 이동 (+ offset_x)
    for poly in fill_list_raw[::2]:
        moved_poly = poly + [offset_x, 0]
        cv2.fillPoly(img, moved_poly, color, cv2.LINE_AA)
        
    # 짝수 번째 (index 1, 3): 왼쪽으로 이동 (- offset_x)
    for poly in fill_list_raw[1::2]:
        moved_poly = poly - [offset_x, 0]
        cv2.fillPoly(img, moved_poly, color, cv2.LINE_AA)

    # --- 테두리 도형들 (Line) ---
    # 홀수 번째: 오른쪽으로 이동
    for poly in line_list_raw[::2]:
        moved_poly = poly + [offset_x, 0]
        cv2.polylines(img, moved_poly, True, color, 1, cv2.LINE_AA)
        
    # 짝수 번째: 왼쪽으로 이동
    for poly in line_list_raw[1::2]:
        moved_poly = poly - [offset_x, 0]
        cv2.polylines(img, moved_poly, True, color, 1, cv2.LINE_AA)

    # --- 원 그리기 ---
    # 홀수 번째 원 (0, 2): 오른쪽
    for i in [0, 2]:
        cx, cy = circle_centers_raw[i]
        cv2.circle(img, (cx + offset_x, cy), radius, circle_colors[i], cv2.FILLED, cv2.LINE_AA)
        
    # 짝수 번째 원 (1, 3): 왼쪽
    for i in [1, 3]:
        cx, cy = circle_centers_raw[i]
        cv2.circle(img, (cx - offset_x, cy), radius, circle_colors[i], cv2.FILLED, cv2.LINE_AA)

    # 4. 상태 업데이트
    radius += rad_direction
    if radius >= 50 or radius <= 30: rad_direction *= -1

    # X축 이동 애니메이션 (0 ~ 100)
    offset_x += x_direction
    if offset_x >= 100 or offset_x <= 0:
        x_direction *= -1

    cv2.imshow('ZigZag Shapes', img)
    if cv2.waitKey(20) & 0xFF == ord('q'):
        break

cv2.destroyAllWindows()
cv2.waitKey(1) # macOS 전용 버그 픽스용 한 번 더 호출